# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

require "../spec_helper"

# Unit tests for Build::AddonServicesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe "AddonServicesApi" do
  describe "test an instance of AddonServicesApi" do
    it "should create an instance of AddonServicesApi" do
      api_instance = Build::AddonServicesApi.new
      expect(api_instance).to be_instance_of(Build::AddonServicesApi)
    end
  end

  # unit tests for list_addon_service_plans
  # list plans for addon service
  # List all visible plans for an addon service
  # @param name Addon service name
  # @param [Hash] opts the optional parameters
  # @return [Array(AddonPlanCatalogItem)]
  describe "list_addon_service_plans test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for list_addon_services
  # list addon services
  # List all visible addon services from the catalog
  # @param [Hash] opts the optional parameters
  # @return [Array(AddonServiceCatalogItem)]
  describe "list_addon_services test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
