# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

require "../spec_helper"

# Unit tests for Build::AddonsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe "AddonsApi" do
  describe "test an instance of AddonsApi" do
    it "should create an instance of AddonsApi" do
      api_instance = Build::AddonsApi.new
      expect(api_instance).to be_instance_of(Build::AddonsApi)
    end
  end

  # unit tests for create_addon
  # create addon
  # Create and provision a new addon for an app
  # @param app_id_or_name App ID or name
  # @param [Hash] opts the optional parameters
  # @option opts [CreateAddonRequest] :create_addon_request 
  # @return [Addon]
  describe "create_addon test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for destroy_addon
  # destroy addon
  # Destroy an addon (deprovisions and removes from all attached apps)
  # @param app_id_or_name App ID or name
  # @param addon_id_or_name Addon ID or name
  # @param [Hash] opts the optional parameters
  # @return [Addon]
  describe "destroy_addon test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for get_addon
  # show addon
  # Get info about an addon
  # @param app_id_or_name App ID or name
  # @param addon_id_or_name Addon ID or name
  # @param [Hash] opts the optional parameters
  # @return [Addon]
  describe "get_addon test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for list_app_addons
  # list addons
  # List all addons for an app
  # @param app_id_or_name App ID or name
  # @param [Hash] opts the optional parameters
  # @return [Array(Addon)]
  describe "list_app_addons test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
