# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

require "../spec_helper"

# Unit tests for Build::CollaboratorsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe "CollaboratorsApi" do
  describe "test an instance of CollaboratorsApi" do
    it "should create an instance of CollaboratorsApi" do
      api_instance = Build::CollaboratorsApi.new
      expect(api_instance).to be_instance_of(Build::CollaboratorsApi)
    end
  end

  # unit tests for api_v1_apps_app_id_collaborators_get
  # List collaborators for an app
  # @param app_id 
  # @param [Hash] opts the optional parameters
  # @return [Array(Collaborator)]
  describe "api_v1_apps_app_id_collaborators_get test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
