# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

require "../spec_helper"

# Unit tests for Build::DomainsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe "DomainsApi" do
  describe "test an instance of DomainsApi" do
    it "should create an instance of DomainsApi" do
      api_instance = Build::DomainsApi.new
      expect(api_instance).to be_instance_of(Build::DomainsApi)
    end
  end

  # unit tests for clear_domains
  # clear all domains
  # Clear all custom domains from an app
  # @param app_id_or_name app id or name
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "clear_domains test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for create_domain
  # create domain
  # Add a domain to an app
  # @param app_id_or_name app id or name
  # @param [Hash] opts the optional parameters
  # @option opts [CreateDomainRequest] :create_domain_request 
  # @return [Domain]
  describe "create_domain test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for list_domains
  # list domains
  # List all domains for an app (platform domain + custom domains)
  # @param app_id_or_name app id or name
  # @param [Hash] opts the optional parameters
  # @return [Array(Domain)]
  describe "list_domains test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for remove_domain
  # remove domain
  # Remove a domain from an app
  # @param app_id_or_name app id or name
  # @param domain_id domain id or hostname
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "remove_domain test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for show_domain
  # show domain
  # Get detailed information about a specific domain
  # @param app_id_or_name app id or name
  # @param domain_id domain id or hostname
  # @param [Hash] opts the optional parameters
  # @return [Domain]
  describe "show_domain test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for update_domain
  # update domain
  # Update a domain (e.g., change SSL certificate)
  # @param app_id_or_name app id or name
  # @param domain_id domain id or hostname
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateDomainRequest] :update_domain_request 
  # @return [Domain]
  describe "update_domain test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
