# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

require "../spec_helper"

# Unit tests for Build::FormationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe "FormationApi" do
  describe "test an instance of FormationApi" do
    it "should create an instance of FormationApi" do
      api_instance = Build::FormationApi.new
      expect(api_instance).to be_instance_of(Build::FormationApi)
    end
  end

  # unit tests for update_formation
  # batch update formation
  # Batch update process formation (Heroku-compatible)
  # @param app_id_or_name App ID or name
  # @param [Hash] opts the optional parameters
  # @option opts [FormationBatchUpdateRequest] :formation_batch_update_request 
  # @return [Hash(String, Object)]
  describe "update_formation test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
