# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.11.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for Build::PipelinesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "PipelinesApi" do
  describe "test an instance of PipelinesApi" do
    it "should create an instance of PipelinesApi" do
      api_instance = Build::PipelinesApi.new
      # TODO expect(api_instance).to be_instance_of(Build::PipelinesApi)
    end
  end

  # unit tests for get_pipeline
  # get a specific pipeline
  # Retrieves details for a specific pipeline
  # @param id Pipeline ID
  # @param [Hash] opts the optional parameters
  # @return [Pipeline]
  describe "get_pipeline test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for list_pipelines
  # list pipelines
  # Lists all pipelines accessible to the current user
  # @param [Hash] opts the optional parameters
  # @return [Array(Pipeline)]
  describe "list_pipelines test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
