# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

require "../spec_helper"

# Unit tests for Build::PipelinePromotionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe "PipelinePromotionsApi" do
  describe "test an instance of PipelinePromotionsApi" do
    it "should create an instance of PipelinePromotionsApi" do
      api_instance = Build::PipelinePromotionsApi.new
      expect(api_instance).to be_instance_of(Build::PipelinePromotionsApi)
    end
  end

  # unit tests for create_pipeline_promotion
  # create a pipeline promotion
  # Creates a promotion from a source app to one or more target apps. Returns immediately with pending status — clients poll GET .../promotions/:id for completion.
  # @param pipeline_id Pipeline ID
  # @param [Hash] opts the optional parameters
  # @option opts [CreatePipelinePromotionRequest] :create_pipeline_promotion_request 
  # @return [PipelinePromotion]
  describe "create_pipeline_promotion test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for get_pipeline_promotion
  # get promotion status
  # Returns aggregate promotion status. Clients poll this until status is no longer pending.
  # @param pipeline_id Pipeline ID
  # @param id Promotion group ID
  # @param [Hash] opts the optional parameters
  # @return [PipelinePromotion]
  describe "get_pipeline_promotion test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for get_pipeline_promotion_targets
  # list promotion targets
  # Returns per-target status with error_message on failure.
  # @param pipeline_id Pipeline ID
  # @param id Promotion group ID
  # @param [Hash] opts the optional parameters
  # @return [Array(PromotionTarget)]
  describe "get_pipeline_promotion_targets test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
