# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.6.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for Build::ApiV1AppsIdBuildsPostRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Build::ApiV1AppsIdBuildsPostRequest do

  describe "test an instance of ApiV1AppsIdBuildsPostRequest" do
    it "should create an instance of ApiV1AppsIdBuildsPostRequest" do
      #instance = Build::ApiV1AppsIdBuildsPostRequest.new
      #expect(instance).to be_instance_of(Build::ApiV1AppsIdBuildsPostRequest)
    end
  end
  describe "test attribute 'branch'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'commitish'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'description'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
