# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.6.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for OpenAPIClient::AppBuildpacksInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenAPIClient::AppBuildpacksInner do

  describe "test an instance of AppBuildpacksInner" do
    it "should create an instance of AppBuildpacksInner" do
      #instance = OpenAPIClient::AppBuildpacksInner.new
      #expect(instance).to be_instance_of(OpenAPIClient::AppBuildpacksInner)
    end
  end
  describe "test attribute 'url'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
