# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

require "../spec_helper"

# Unit tests for Build::BuildpackInstallation
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe Build::BuildpackInstallation do

  describe "test an instance of BuildpackInstallation" do
    skip "should create an instance of BuildpackInstallation" do
      #instance = Build::BuildpackInstallation.new
      #expect(instance).to be_instance_of(Build::BuildpackInstallation)
    end
  end
  describe "test attribute 'ordinal'" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'buildpack'" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
