# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.8.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for Build::ConfigVars200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Build::ConfigVars200Response do

  describe "test an instance of ConfigVars200Response" do
    it "should create an instance of ConfigVars200Response" do
      #instance = Build::ConfigVars200Response.new
      #expect(instance).to be_instance_of(Build::ConfigVars200Response)
    end
  end
  describe "test attribute 'additional_properties'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
