# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

require "../spec_helper"

# Unit tests for Build::CreateDomainRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe Build::CreateDomainRequest do

  describe "test an instance of CreateDomainRequest" do
    skip "should create an instance of CreateDomainRequest" do
      #instance = Build::CreateDomainRequest.new
      #expect(instance).to be_instance_of(Build::CreateDomainRequest)
    end
  end
  describe "test attribute 'hostname'" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'cert'" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
