# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.11.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for Build::Error
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Build::Error do

  describe "test an instance of Error" do
    it "should create an instance of Error" do
      #instance = Build::Error.new
      #expect(instance).to be_instance_of(Build::Error)
    end
  end
  describe "test attribute 'error'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
