# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.13.0
#

require "../spec_helper"

# Unit tests for Build::ExecDyno200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe Build::ExecDyno200Response do

  describe "test an instance of ExecDyno200Response" do
    skip "should create an instance of ExecDyno200Response" do
      #instance = Build::ExecDyno200Response.new
      #expect(instance).to be_instance_of(Build::ExecDyno200Response)
    end
  end
  describe "test attribute 'output'" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
