# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.8.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for Build::SetConfigVarsRequestValue
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Build::SetConfigVarsRequestValue do
  describe ".openapi_one_of" do
    it "lists the items referenced in the oneOf array" do
      expect(described_class.openapi_one_of).to_not be_empty
    end
  end

  describe ".build" do
    it "returns the correct model" do
    end
  end
end
