# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

require "uri"

module OpenAPIClient
  class AddonAttachmentsApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # create addon attachment
    # Attach an addon to an app
    # @return [AddonAttachment]
    def create_addon_attachment(create_addon_attachment_request : CreateAddonAttachmentRequest? = nil)
      data, _status_code, _headers = create_addon_attachment_with_http_info(create_addon_attachment_request)
      data
    end

    # create addon attachment
    # Attach an addon to an app
    # @return [Array<(AddonAttachment, Integer, Hash)>] AddonAttachment data, response status code and response headers
    def create_addon_attachment_with_http_info(create_addon_attachment_request : CreateAddonAttachmentRequest? = nil)
      if @api_client.config.debugging
        Log.debug {"Calling API: AddonAttachmentsApi.create_addon_attachment ..."}
      end
      # resource path
      local_var_path = "/api/v1/addon-attachments"

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = create_addon_attachment_request.to_json

      # return_type
      return_type = "AddonAttachment"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"AddonAttachmentsApi.create_addon_attachment",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: AddonAttachmentsApi#create_addon_attachment\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return AddonAttachment.from_json(data), status_code, headers
    end

    # delete addon attachment
    # Detach an addon from an app
    # @param addon_attachment_id [String] Addon attachment ID
    # @return [AddonAttachment]
    def delete_addon_attachment(addon_attachment_id : String)
      data, _status_code, _headers = delete_addon_attachment_with_http_info(addon_attachment_id)
      data
    end

    # delete addon attachment
    # Detach an addon from an app
    # @param addon_attachment_id [String] Addon attachment ID
    # @return [Array<(AddonAttachment, Integer, Hash)>] AddonAttachment data, response status code and response headers
    def delete_addon_attachment_with_http_info(addon_attachment_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: AddonAttachmentsApi.delete_addon_attachment ..."}
      end
      # verify the required parameter "addon_attachment_id" is set
      if @api_client.config.client_side_validation && addon_attachment_id.nil?
        raise ArgumentError.new("Missing the required parameter 'addon_attachment_id' when calling AddonAttachmentsApi.delete_addon_attachment")
      end
      # resource path
      local_var_path = "/api/v1/addon-attachments/{addon_attachment_id}".sub("{" + "addon_attachment_id" + "}", URI.encode_path(addon_attachment_id.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "AddonAttachment"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:DELETE,
                                                        local_var_path,
                                                        :"AddonAttachmentsApi.delete_addon_attachment",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: AddonAttachmentsApi#delete_addon_attachment\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return AddonAttachment.from_json(data), status_code, headers
    end

    # show addon attachment
    # Get info about an addon attachment
    # @param addon_attachment_id [String] Addon attachment ID
    # @return [AddonAttachment]
    def get_addon_attachment(addon_attachment_id : String)
      data, _status_code, _headers = get_addon_attachment_with_http_info(addon_attachment_id)
      data
    end

    # show addon attachment
    # Get info about an addon attachment
    # @param addon_attachment_id [String] Addon attachment ID
    # @return [Array<(AddonAttachment, Integer, Hash)>] AddonAttachment data, response status code and response headers
    def get_addon_attachment_with_http_info(addon_attachment_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: AddonAttachmentsApi.get_addon_attachment ..."}
      end
      # verify the required parameter "addon_attachment_id" is set
      if @api_client.config.client_side_validation && addon_attachment_id.nil?
        raise ArgumentError.new("Missing the required parameter 'addon_attachment_id' when calling AddonAttachmentsApi.get_addon_attachment")
      end
      # resource path
      local_var_path = "/api/v1/addon-attachments/{addon_attachment_id}".sub("{" + "addon_attachment_id" + "}", URI.encode_path(addon_attachment_id.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "AddonAttachment"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"AddonAttachmentsApi.get_addon_attachment",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: AddonAttachmentsApi#get_addon_attachment\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return AddonAttachment.from_json(data), status_code, headers
    end

    # list addon attachments
    # List all addon attachments
    # @return [Array(AddonAttachment)]
    def list_addon_attachments()
      data, _status_code, _headers = list_addon_attachments_with_http_info()
      data
    end

    # list addon attachments
    # List all addon attachments
    # @return [Array<(Array(AddonAttachment), Integer, Hash)>] Array(AddonAttachment) data, response status code and response headers
    def list_addon_attachments_with_http_info()
      if @api_client.config.debugging
        Log.debug {"Calling API: AddonAttachmentsApi.list_addon_attachments ..."}
      end
      # resource path
      local_var_path = "/api/v1/addon-attachments"

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "Array(AddonAttachment)"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"AddonAttachmentsApi.list_addon_attachments",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: AddonAttachmentsApi#list_addon_attachments\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Array(AddonAttachment).from_json(data), status_code, headers
    end
  end
end
