# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

require "uri"

module Build
  class AddonServicesApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # list plans for addon service
    # List all visible plans for an addon service
    # @param name [String] Addon service name
    # @return [Array(AddonPlanCatalogItem)]
    def list_addon_service_plans(name : String)
      data, _status_code, _headers = list_addon_service_plans_with_http_info(name)
      data
    end

    # list plans for addon service
    # List all visible plans for an addon service
    # @param name [String] Addon service name
    # @return [Array<(Array(AddonPlanCatalogItem), Integer, Hash)>] Array(AddonPlanCatalogItem) data, response status code and response headers
    def list_addon_service_plans_with_http_info(name : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: AddonServicesApi.list_addon_service_plans ..."}
      end
      # verify the required parameter "name" is set
      if @api_client.config.client_side_validation && name.nil?
        raise ArgumentError.new("Missing the required parameter 'name' when calling AddonServicesApi.list_addon_service_plans")
      end
      # resource path
      local_var_path = "/api/v1/addon-services/{name}/plans".sub("{" + "name" + "}", URI.encode_path(name.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "Array(AddonPlanCatalogItem)"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"AddonServicesApi.list_addon_service_plans",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: AddonServicesApi#list_addon_service_plans\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Array(AddonPlanCatalogItem).from_json(data), status_code, headers
    end

    # list addon services
    # List all visible addon services from the catalog
    # @return [Array(AddonServiceCatalogItem)]
    def list_addon_services()
      data, _status_code, _headers = list_addon_services_with_http_info()
      data
    end

    # list addon services
    # List all visible addon services from the catalog
    # @return [Array<(Array(AddonServiceCatalogItem), Integer, Hash)>] Array(AddonServiceCatalogItem) data, response status code and response headers
    def list_addon_services_with_http_info()
      if @api_client.config.debugging
        Log.debug {"Calling API: AddonServicesApi.list_addon_services ..."}
      end
      # resource path
      local_var_path = "/api/v1/addon-services"

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "Array(AddonServiceCatalogItem)"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"AddonServicesApi.list_addon_services",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: AddonServicesApi#list_addon_services\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Array(AddonServiceCatalogItem).from_json(data), status_code, headers
    end
  end
end
