# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

require "uri"

module Build
  class AddonsApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # create addon
    # Create and provision a new addon for an app
    # @param app_id_or_name [String] App ID or name
    # @return [Addon]
    def create_addon(app_id_or_name : String, create_addon_request : CreateAddonRequest? = nil)
      data, _status_code, _headers = create_addon_with_http_info(app_id_or_name, create_addon_request)
      data
    end

    # create addon
    # Create and provision a new addon for an app
    # @param app_id_or_name [String] App ID or name
    # @return [Array<(Addon, Integer, Hash)>] Addon data, response status code and response headers
    def create_addon_with_http_info(app_id_or_name : String, create_addon_request : CreateAddonRequest? = nil)
      if @api_client.config.debugging
        Log.debug {"Calling API: AddonsApi.create_addon ..."}
      end
      # verify the required parameter "app_id_or_name" is set
      if @api_client.config.client_side_validation && app_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'app_id_or_name' when calling AddonsApi.create_addon")
      end
      # resource path
      local_var_path = "/api/v1/apps/{app_id_or_name}/addons".sub("{" + "app_id_or_name" + "}", URI.encode_path(app_id_or_name.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = create_addon_request.to_json

      # return_type
      return_type = "Addon"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"AddonsApi.create_addon",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: AddonsApi#create_addon\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Addon.from_json(data), status_code, headers
    end

    # destroy addon
    # Destroy an addon (deprovisions and removes from all attached apps)
    # @param app_id_or_name [String] App ID or name
    # @param addon_id_or_name [String] Addon ID or name
    # @return [Addon]
    def destroy_addon(app_id_or_name : String, addon_id_or_name : String)
      data, _status_code, _headers = destroy_addon_with_http_info(app_id_or_name, addon_id_or_name)
      data
    end

    # destroy addon
    # Destroy an addon (deprovisions and removes from all attached apps)
    # @param app_id_or_name [String] App ID or name
    # @param addon_id_or_name [String] Addon ID or name
    # @return [Array<(Addon, Integer, Hash)>] Addon data, response status code and response headers
    def destroy_addon_with_http_info(app_id_or_name : String, addon_id_or_name : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: AddonsApi.destroy_addon ..."}
      end
      # verify the required parameter "app_id_or_name" is set
      if @api_client.config.client_side_validation && app_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'app_id_or_name' when calling AddonsApi.destroy_addon")
      end
      # verify the required parameter "addon_id_or_name" is set
      if @api_client.config.client_side_validation && addon_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'addon_id_or_name' when calling AddonsApi.destroy_addon")
      end
      # resource path
      local_var_path = "/api/v1/apps/{app_id_or_name}/addons/{addon_id_or_name}".sub("{" + "app_id_or_name" + "}", URI.encode_path(app_id_or_name.to_s)).sub("{" + "addon_id_or_name" + "}", URI.encode_path(addon_id_or_name.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "Addon"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:DELETE,
                                                        local_var_path,
                                                        :"AddonsApi.destroy_addon",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: AddonsApi#destroy_addon\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Addon.from_json(data), status_code, headers
    end

    # show addon
    # Get info about an addon
    # @param app_id_or_name [String] App ID or name
    # @param addon_id_or_name [String] Addon ID or name
    # @return [Addon]
    def get_addon(app_id_or_name : String, addon_id_or_name : String)
      data, _status_code, _headers = get_addon_with_http_info(app_id_or_name, addon_id_or_name)
      data
    end

    # show addon
    # Get info about an addon
    # @param app_id_or_name [String] App ID or name
    # @param addon_id_or_name [String] Addon ID or name
    # @return [Array<(Addon, Integer, Hash)>] Addon data, response status code and response headers
    def get_addon_with_http_info(app_id_or_name : String, addon_id_or_name : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: AddonsApi.get_addon ..."}
      end
      # verify the required parameter "app_id_or_name" is set
      if @api_client.config.client_side_validation && app_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'app_id_or_name' when calling AddonsApi.get_addon")
      end
      # verify the required parameter "addon_id_or_name" is set
      if @api_client.config.client_side_validation && addon_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'addon_id_or_name' when calling AddonsApi.get_addon")
      end
      # resource path
      local_var_path = "/api/v1/apps/{app_id_or_name}/addons/{addon_id_or_name}".sub("{" + "app_id_or_name" + "}", URI.encode_path(app_id_or_name.to_s)).sub("{" + "addon_id_or_name" + "}", URI.encode_path(addon_id_or_name.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "Addon"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"AddonsApi.get_addon",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: AddonsApi#get_addon\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Addon.from_json(data), status_code, headers
    end

    # show addon info
    # Get detailed addon info including attachments
    # @param id [String] Addon ID or name
    # @return [AddonWithAttachments]
    def get_addon_info(id : String)
      data, _status_code, _headers = get_addon_info_with_http_info(id)
      data
    end

    # show addon info
    # Get detailed addon info including attachments
    # @param id [String] Addon ID or name
    # @return [Array<(AddonWithAttachments, Integer, Hash)>] AddonWithAttachments data, response status code and response headers
    def get_addon_info_with_http_info(id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: AddonsApi.get_addon_info ..."}
      end
      # verify the required parameter "id" is set
      if @api_client.config.client_side_validation && id.nil?
        raise ArgumentError.new("Missing the required parameter 'id' when calling AddonsApi.get_addon_info")
      end
      # resource path
      local_var_path = "/api/v1/addons/{id}".sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "AddonWithAttachments"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"AddonsApi.get_addon_info",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: AddonsApi#get_addon_info\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return AddonWithAttachments.from_json(data), status_code, headers
    end

    # list addons
    # List all addons for an app
    # @param app_id_or_name [String] App ID or name
    # @return [Array(Addon)]
    def list_app_addons(app_id_or_name : String)
      data, _status_code, _headers = list_app_addons_with_http_info(app_id_or_name)
      data
    end

    # list addons
    # List all addons for an app
    # @param app_id_or_name [String] App ID or name
    # @return [Array<(Array(Addon), Integer, Hash)>] Array(Addon) data, response status code and response headers
    def list_app_addons_with_http_info(app_id_or_name : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: AddonsApi.list_app_addons ..."}
      end
      # verify the required parameter "app_id_or_name" is set
      if @api_client.config.client_side_validation && app_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'app_id_or_name' when calling AddonsApi.list_app_addons")
      end
      # resource path
      local_var_path = "/api/v1/apps/{app_id_or_name}/addons".sub("{" + "app_id_or_name" + "}", URI.encode_path(app_id_or_name.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "Array(Addon)"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"AddonsApi.list_app_addons",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: AddonsApi#list_app_addons\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Array(Addon).from_json(data), status_code, headers
    end

    # list team addons
    # List all addons for a team (across all apps)
    # @param team_id [String] Team ID or name
    # @return [Array(Addon)]
    def list_team_addons(team_id : String)
      data, _status_code, _headers = list_team_addons_with_http_info(team_id)
      data
    end

    # list team addons
    # List all addons for a team (across all apps)
    # @param team_id [String] Team ID or name
    # @return [Array<(Array(Addon), Integer, Hash)>] Array(Addon) data, response status code and response headers
    def list_team_addons_with_http_info(team_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: AddonsApi.list_team_addons ..."}
      end
      # verify the required parameter "team_id" is set
      if @api_client.config.client_side_validation && team_id.nil?
        raise ArgumentError.new("Missing the required parameter 'team_id' when calling AddonsApi.list_team_addons")
      end
      # resource path
      local_var_path = "/api/v1/teams/{team_id}/addons".sub("{" + "team_id" + "}", URI.encode_path(team_id.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "Array(Addon)"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"AddonsApi.list_team_addons",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: AddonsApi#list_team_addons\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Array(Addon).from_json(data), status_code, headers
    end
  end
end
