# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

require "uri"

module Build
  class BuildpacksApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # list buildpacks
    # List an app's buildpack installations in execution order
    # @param app_id_or_name [String] App ID or name
    # @return [Array(BuildpackInstallation)]
    def list_buildpacks(app_id_or_name : String)
      data, _status_code, _headers = list_buildpacks_with_http_info(app_id_or_name)
      data
    end

    # list buildpacks
    # List an app&#39;s buildpack installations in execution order
    # @param app_id_or_name [String] App ID or name
    # @return [Array<(Array(BuildpackInstallation), Integer, Hash)>] Array(BuildpackInstallation) data, response status code and response headers
    def list_buildpacks_with_http_info(app_id_or_name : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: BuildpacksApi.list_buildpacks ..."}
      end
      # verify the required parameter "app_id_or_name" is set
      if @api_client.config.client_side_validation && app_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'app_id_or_name' when calling BuildpacksApi.list_buildpacks")
      end
      # resource path
      local_var_path = "/api/v1/apps/{app_id_or_name}/buildpacks".sub("{" + "app_id_or_name" + "}", URI.encode_path(app_id_or_name.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "Array(BuildpackInstallation)"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"BuildpacksApi.list_buildpacks",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: BuildpacksApi#list_buildpacks\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Array(BuildpackInstallation).from_json(data), status_code, headers
    end

    # update buildpacks
    # Replace an app's buildpack list. Order determines execution order.
    # @param app_id_or_name [String] App ID or name
    # @return [Array(BuildpackInstallation)]
    def update_buildpacks(app_id_or_name : String, update_buildpacks_request : UpdateBuildpacksRequest? = nil)
      data, _status_code, _headers = update_buildpacks_with_http_info(app_id_or_name, update_buildpacks_request)
      data
    end

    # update buildpacks
    # Replace an app&#39;s buildpack list. Order determines execution order.
    # @param app_id_or_name [String] App ID or name
    # @return [Array<(Array(BuildpackInstallation), Integer, Hash)>] Array(BuildpackInstallation) data, response status code and response headers
    def update_buildpacks_with_http_info(app_id_or_name : String, update_buildpacks_request : UpdateBuildpacksRequest? = nil)
      if @api_client.config.debugging
        Log.debug {"Calling API: BuildpacksApi.update_buildpacks ..."}
      end
      # verify the required parameter "app_id_or_name" is set
      if @api_client.config.client_side_validation && app_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'app_id_or_name' when calling BuildpacksApi.update_buildpacks")
      end
      # resource path
      local_var_path = "/api/v1/apps/{app_id_or_name}/buildpacks".sub("{" + "app_id_or_name" + "}", URI.encode_path(app_id_or_name.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = update_buildpacks_request.to_json

      # return_type
      return_type = "Array(BuildpackInstallation)"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:PUT,
                                                        local_var_path,
                                                        :"BuildpacksApi.update_buildpacks",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: BuildpacksApi#update_buildpacks\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Array(BuildpackInstallation).from_json(data), status_code, headers
    end
  end
end
