# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

require "uri"

module Build
  class CollaboratorsApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # List collaborators for an app
    # @param app_id [String] 
    # @return [Array(Collaborator)]
    def api_v1_apps_app_id_collaborators_get(app_id : String)
      data, _status_code, _headers = api_v1_apps_app_id_collaborators_get_with_http_info(app_id)
      data
    end

    # List collaborators for an app
    # @param app_id [String] 
    # @return [Array<(Array(Collaborator), Integer, Hash)>] Array(Collaborator) data, response status code and response headers
    def api_v1_apps_app_id_collaborators_get_with_http_info(app_id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: CollaboratorsApi.api_v1_apps_app_id_collaborators_get ..."}
      end
      # verify the required parameter "app_id" is set
      if @api_client.config.client_side_validation && app_id.nil?
        raise ArgumentError.new("Missing the required parameter 'app_id' when calling CollaboratorsApi.api_v1_apps_app_id_collaborators_get")
      end
      # resource path
      local_var_path = "/api/v1/apps/{app_id}/collaborators".sub("{" + "app_id" + "}", URI.encode_path(app_id.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "Array(Collaborator)"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"CollaboratorsApi.api_v1_apps_app_id_collaborators_get",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: CollaboratorsApi#api_v1_apps_app_id_collaborators_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Array(Collaborator).from_json(data), status_code, headers
    end
  end
end
