# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.11.0
#

require "uri"

module Build
  class DefaultApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # show app
    # @param app_id_or_name [String] app id or name
    # @return [App]
    def app(app_id_or_name : String)
      data, _status_code, _headers = app_with_http_info(app_id_or_name)
      data
    end

    # show app
    # @param app_id_or_name [String] app id or name
    # @return [Array<(App, Integer, Hash)>] App data, response status code and response headers
    def app_with_http_info(app_id_or_name : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.app ..."}
      end
      # verify the required parameter "app_id_or_name" is set
      if @api_client.config.client_side_validation && app_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'app_id_or_name' when calling DefaultApi.app")
      end
      # resource path
      local_var_path = "/api/v1/apps/{app_id_or_name}".sub("{" + "app_id_or_name" + "}", URI.encode_path(app_id_or_name.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "App"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DefaultApi.app",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#app\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return App.from_json(data), status_code, headers
    end

    # list apps
    # List all apps
    # @return [Array(App)]
    def apps(team_id : String?)
      data, _status_code, _headers = apps_with_http_info(team_id)
      data
    end

    # list apps
    # List all apps
    # @return [Array<(Array(App), Integer, Hash)>] Array(App) data, response status code and response headers
    def apps_with_http_info(team_id : String?)
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.apps ..."}
      end
      # resource path
      local_var_path = "/api/v1/apps"

      # query parameters
      query_params = Hash(String, String).new
      query_params["team_id"] = team_id.to_s unless team_id.nil?

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "Array(App)"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DefaultApi.apps",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#apps\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Array(App).from_json(data), status_code, headers
    end

    # list all config-vars
    # @param app_id_or_name [String] app id or name
    # @return [Hash(String, String)]
    def config_vars(app_id_or_name : String)
      data, _status_code, _headers = config_vars_with_http_info(app_id_or_name)
      data
    end

    # list all config-vars
    # @param app_id_or_name [String] app id or name
    # @return [Array<(Hash(String, String), Integer, Hash)>] Hash(String, String) data, response status code and response headers
    def config_vars_with_http_info(app_id_or_name : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.config_vars ..."}
      end
      # verify the required parameter "app_id_or_name" is set
      if @api_client.config.client_side_validation && app_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'app_id_or_name' when calling DefaultApi.config_vars")
      end
      # resource path
      local_var_path = "/api/v1/apps/{app_id_or_name}/config-vars".sub("{" + "app_id_or_name" + "}", URI.encode_path(app_id_or_name.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "Hash(String, String)"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DefaultApi.config_vars",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#config_vars\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Hash(String, String).from_json(data), status_code, headers
    end

    # create app
    # @return [App]
    def create_app(create_app_request : CreateAppRequest?)
      data, _status_code, _headers = create_app_with_http_info(create_app_request)
      data
    end

    # create app
    # @return [Array<(App, Integer, Hash)>] App data, response status code and response headers
    def create_app_with_http_info(create_app_request : CreateAppRequest?)
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.create_app ..."}
      end
      # resource path
      local_var_path = "/api/v1/apps"

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = create_app_request.to_json

      # return_type
      return_type = "App"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"DefaultApi.create_app",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#create_app\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return App.from_json(data), status_code, headers
    end

    # create build
    # @param app_id_or_name [String] app id or name
    # @return [nil]
    def create_build(app_id_or_name : String, create_build_request : CreateBuildRequest?)
      create_build_with_http_info(app_id_or_name, create_build_request)
      nil
    end

    # create build
    # @param app_id_or_name [String] app id or name
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def create_build_with_http_info(app_id_or_name : String, create_build_request : CreateBuildRequest?)
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.create_build ..."}
      end
      # verify the required parameter "app_id_or_name" is set
      if @api_client.config.client_side_validation && app_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'app_id_or_name' when calling DefaultApi.create_build")
      end
      # resource path
      local_var_path = "/api/v1/apps/{app_id_or_name}/builds".sub("{" + "app_id_or_name" + "}", URI.encode_path(app_id_or_name.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = create_build_request.to_json

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"DefaultApi.create_build",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#create_build\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # create a namespace
    # Create a namespace
    # @return [Namespace]
    def create_namespace(create_namespace_request : CreateNamespaceRequest?)
      data, _status_code, _headers = create_namespace_with_http_info(create_namespace_request)
      data
    end

    # create a namespace
    # Create a namespace
    # @return [Array<(Namespace, Integer, Hash)>] Namespace data, response status code and response headers
    def create_namespace_with_http_info(create_namespace_request : CreateNamespaceRequest?)
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.create_namespace ..."}
      end
      # resource path
      local_var_path = "/api/v1/namespaces"

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = create_namespace_request.to_json

      # return_type
      return_type = "Namespace"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"DefaultApi.create_namespace",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#create_namespace\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Namespace.from_json(data), status_code, headers
    end

    # delete config-var
    # Delete a config-var
    # @param app_id_or_name [String] app id or name
    # @param key [String] config var key
    # @return [nil]
    def delete_config_var(app_id_or_name : String, key : String)
      delete_config_var_with_http_info(app_id_or_name, key)
      nil
    end

    # delete config-var
    # Delete a config-var
    # @param app_id_or_name [String] app id or name
    # @param key [String] config var key
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def delete_config_var_with_http_info(app_id_or_name : String, key : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.delete_config_var ..."}
      end
      # verify the required parameter "app_id_or_name" is set
      if @api_client.config.client_side_validation && app_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'app_id_or_name' when calling DefaultApi.delete_config_var")
      end
      # verify the required parameter "key" is set
      if @api_client.config.client_side_validation && key.nil?
        raise ArgumentError.new("Missing the required parameter 'key' when calling DefaultApi.delete_config_var")
      end
      # resource path
      local_var_path = "/api/v1/apps/{app_id_or_name}/config-vars/{key}".sub("{" + "app_id_or_name" + "}", URI.encode_path(app_id_or_name.to_s)).sub("{" + "key" + "}", URI.encode_path(key.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:DELETE,
                                                        local_var_path,
                                                        :"DefaultApi.delete_config_var",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#delete_config_var\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # delete a namespace
    # Delete a namespace
    # @param namespace_id_or_name [String] Namespace name or ID
    # @return [nil]
    def delete_namespace(namespace_id_or_name : String)
      delete_namespace_with_http_info(namespace_id_or_name)
      nil
    end

    # delete a namespace
    # Delete a namespace
    # @param namespace_id_or_name [String] Namespace name or ID
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def delete_namespace_with_http_info(namespace_id_or_name : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.delete_namespace ..."}
      end
      # verify the required parameter "namespace_id_or_name" is set
      if @api_client.config.client_side_validation && namespace_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'namespace_id_or_name' when calling DefaultApi.delete_namespace")
      end
      # resource path
      local_var_path = "/api/v1/namespaces/{namespace_id_or_name}".sub("{" + "namespace_id_or_name" + "}", URI.encode_path(namespace_id_or_name.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:DELETE,
                                                        local_var_path,
                                                        :"DefaultApi.delete_namespace",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#delete_namespace\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # exec into dyno
    # @param app_id_or_name [String] app id or name
    # @param dyno [String] dyno name
    # @param dyno_exec_request [DynoExecRequest] 
    # @return [DynoExecResponse]
    def exec_dyno(app_id_or_name : String, dyno : String, dyno_exec_request : DynoExecRequest)
      data, _status_code, _headers = exec_dyno_with_http_info(app_id_or_name, dyno, dyno_exec_request)
      data
    end

    # exec into dyno
    # @param app_id_or_name [String] app id or name
    # @param dyno [String] dyno name
    # @param dyno_exec_request [DynoExecRequest] 
    # @return [Array<(DynoExecResponse, Integer, Hash)>] DynoExecResponse data, response status code and response headers
    def exec_dyno_with_http_info(app_id_or_name : String, dyno : String, dyno_exec_request : DynoExecRequest)
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.exec_dyno ..."}
      end
      # verify the required parameter "app_id_or_name" is set
      if @api_client.config.client_side_validation && app_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'app_id_or_name' when calling DefaultApi.exec_dyno")
      end
      # verify the required parameter "dyno" is set
      if @api_client.config.client_side_validation && dyno.nil?
        raise ArgumentError.new("Missing the required parameter 'dyno' when calling DefaultApi.exec_dyno")
      end
      # verify the required parameter "dyno_exec_request" is set
      if @api_client.config.client_side_validation && dyno_exec_request.nil?
        raise ArgumentError.new("Missing the required parameter 'dyno_exec_request' when calling DefaultApi.exec_dyno")
      end
      # resource path
      local_var_path = "/api/v1/apps/{app_id_or_name}/dynos/{dyno}/exec".sub("{" + "app_id_or_name" + "}", URI.encode_path(app_id_or_name.to_s)).sub("{" + "dyno" + "}", URI.encode_path(dyno.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = dyno_exec_request.to_json

      # return_type
      return_type = "DynoExecResponse"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"DefaultApi.exec_dyno",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#exec_dyno\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return DynoExecResponse.from_json(data), status_code, headers
    end

    # list dynos
    # @param app_id_or_name [String] app id or name
    # @return [Array(Dyno)]
    def list_dynos(app_id_or_name : String)
      data, _status_code, _headers = list_dynos_with_http_info(app_id_or_name)
      data
    end

    # list dynos
    # @param app_id_or_name [String] app id or name
    # @return [Array<(Array(Dyno), Integer, Hash)>] Array(Dyno) data, response status code and response headers
    def list_dynos_with_http_info(app_id_or_name : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.list_dynos ..."}
      end
      # verify the required parameter "app_id_or_name" is set
      if @api_client.config.client_side_validation && app_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'app_id_or_name' when calling DefaultApi.list_dynos")
      end
      # resource path
      local_var_path = "/api/v1/apps/{app_id_or_name}/dynos/list".sub("{" + "app_id_or_name" + "}", URI.encode_path(app_id_or_name.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "Array(Dyno)"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DefaultApi.list_dynos",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#list_dynos\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Array(Dyno).from_json(data), status_code, headers
    end

    # identity
    # @return [MeResponse]
    def me()
      data, _status_code, _headers = me_with_http_info()
      data
    end

    # identity
    # @return [Array<(MeResponse, Integer, Hash)>] MeResponse data, response status code and response headers
    def me_with_http_info()
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.me ..."}
      end
      # resource path
      local_var_path = "/api/v1/me"

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "MeResponse"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DefaultApi.me",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#me\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return MeResponse.from_json(data), status_code, headers
    end

    # show namespace
    # Show a namespace
    # @param namespace_id_or_name [String] Namespace name or ID
    # @return [Namespace]
    def namespace(namespace_id_or_name : String)
      data, _status_code, _headers = namespace_with_http_info(namespace_id_or_name)
      data
    end

    # show namespace
    # Show a namespace
    # @param namespace_id_or_name [String] Namespace name or ID
    # @return [Array<(Namespace, Integer, Hash)>] Namespace data, response status code and response headers
    def namespace_with_http_info(namespace_id_or_name : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.namespace ..."}
      end
      # verify the required parameter "namespace_id_or_name" is set
      if @api_client.config.client_side_validation && namespace_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'namespace_id_or_name' when calling DefaultApi.namespace")
      end
      # resource path
      local_var_path = "/api/v1/namespaces/{namespace_id_or_name}".sub("{" + "namespace_id_or_name" + "}", URI.encode_path(namespace_id_or_name.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "Namespace"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DefaultApi.namespace",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#namespace\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Namespace.from_json(data), status_code, headers
    end

    # list all namespaces
    # List all namespaces
    # @return [Array(Namespace)]
    def namespaces()
      data, _status_code, _headers = namespaces_with_http_info()
      data
    end

    # list all namespaces
    # List all namespaces
    # @return [Array<(Array(Namespace), Integer, Hash)>] Array(Namespace) data, response status code and response headers
    def namespaces_with_http_info()
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.namespaces ..."}
      end
      # resource path
      local_var_path = "/api/v1/namespaces"

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "Array(Namespace)"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DefaultApi.namespaces",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#namespaces\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Array(Namespace).from_json(data), status_code, headers
    end

    # kubernetes oidc-login
    # @return [OidcLoginResponse]
    def oidc_login(region : String?)
      data, _status_code, _headers = oidc_login_with_http_info(region)
      data
    end

    # kubernetes oidc-login
    # @return [Array<(OidcLoginResponse, Integer, Hash)>] OidcLoginResponse data, response status code and response headers
    def oidc_login_with_http_info(region : String?)
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.oidc_login ..."}
      end
      # resource path
      local_var_path = "/api/v1/oidc-login"

      # query parameters
      query_params = Hash(String, String).new
      query_params["region"] = region.to_s unless region.nil?

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "OidcLoginResponse"

      # auth_names
      auth_names = ["api_key", "bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DefaultApi.oidc_login",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#oidc_login\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return OidcLoginResponse.from_json(data), status_code, headers
    end

    # restart all dynos
    # @param app_id_or_name [String] app id or name
    # @return [nil]
    def restart_all_dynos(app_id_or_name : String)
      restart_all_dynos_with_http_info(app_id_or_name)
      nil
    end

    # restart all dynos
    # @param app_id_or_name [String] app id or name
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def restart_all_dynos_with_http_info(app_id_or_name : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.restart_all_dynos ..."}
      end
      # verify the required parameter "app_id_or_name" is set
      if @api_client.config.client_side_validation && app_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'app_id_or_name' when calling DefaultApi.restart_all_dynos")
      end
      # resource path
      local_var_path = "/api/v1/apps/{app_id_or_name}/dynos".sub("{" + "app_id_or_name" + "}", URI.encode_path(app_id_or_name.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:DELETE,
                                                        local_var_path,
                                                        :"DefaultApi.restart_all_dynos",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#restart_all_dynos\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # restart specific dyno
    # @param app_id_or_name [String] app id or name
    # @param dyno [String] dyno name
    # @return [nil]
    def restart_dynos(app_id_or_name : String, dyno : String)
      restart_dynos_with_http_info(app_id_or_name, dyno)
      nil
    end

    # restart specific dyno
    # @param app_id_or_name [String] app id or name
    # @param dyno [String] dyno name
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def restart_dynos_with_http_info(app_id_or_name : String, dyno : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.restart_dynos ..."}
      end
      # verify the required parameter "app_id_or_name" is set
      if @api_client.config.client_side_validation && app_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'app_id_or_name' when calling DefaultApi.restart_dynos")
      end
      # verify the required parameter "dyno" is set
      if @api_client.config.client_side_validation && dyno.nil?
        raise ArgumentError.new("Missing the required parameter 'dyno' when calling DefaultApi.restart_dynos")
      end
      # resource path
      local_var_path = "/api/v1/apps/{app_id_or_name}/dynos/{dyno}".sub("{" + "app_id_or_name" + "}", URI.encode_path(app_id_or_name.to_s)).sub("{" + "dyno" + "}", URI.encode_path(dyno.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:DELETE,
                                                        local_var_path,
                                                        :"DefaultApi.restart_dynos",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#restart_dynos\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # set or update config-vars
    # @param app_id_or_name [String] app id or name
    # @return [nil]
    def set_config_vars(app_id_or_name : String, request_body : Hash(String, String)?)
      set_config_vars_with_http_info(app_id_or_name, request_body)
      nil
    end

    # set or update config-vars
    # @param app_id_or_name [String] app id or name
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def set_config_vars_with_http_info(app_id_or_name : String, request_body : Hash(String, String)?)
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.set_config_vars ..."}
      end
      # verify the required parameter "app_id_or_name" is set
      if @api_client.config.client_side_validation && app_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'app_id_or_name' when calling DefaultApi.set_config_vars")
      end
      # resource path
      local_var_path = "/api/v1/apps/{app_id_or_name}/config-vars".sub("{" + "app_id_or_name" + "}", URI.encode_path(app_id_or_name.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = request_body.to_json

      # return_type
      return_type = nil

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:PATCH,
                                                        local_var_path,
                                                        :"DefaultApi.set_config_vars",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#set_config_vars\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # show team
    # Show a team
    # @param id [String] Team name or ID
    # @return [Team]
    def team(id : String)
      data, _status_code, _headers = team_with_http_info(id)
      data
    end

    # show team
    # Show a team
    # @param id [String] Team name or ID
    # @return [Array<(Team, Integer, Hash)>] Team data, response status code and response headers
    def team_with_http_info(id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.team ..."}
      end
      # verify the required parameter "id" is set
      if @api_client.config.client_side_validation && id.nil?
        raise ArgumentError.new("Missing the required parameter 'id' when calling DefaultApi.team")
      end
      # resource path
      local_var_path = "/api/v1/teams/{id}".sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "Team"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DefaultApi.team",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#team\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Team.from_json(data), status_code, headers
    end

    # list all teams
    # List all teams
    # @return [Array(Team)]
    def teams()
      data, _status_code, _headers = teams_with_http_info()
      data
    end

    # list all teams
    # List all teams
    # @return [Array<(Array(Team), Integer, Hash)>] Array(Team) data, response status code and response headers
    def teams_with_http_info()
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.teams ..."}
      end
      # resource path
      local_var_path = "/api/v1/teams"

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "Array(Team)"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DefaultApi.teams",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#teams\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Array(Team).from_json(data), status_code, headers
    end
  end
end
