# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

require "uri"

module Build
  class FormationApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # batch update formation
    # Batch update process formation (Heroku-compatible)
    # @param app_id_or_name [String] App ID or name
    # @return [Hash(String, Object)]
    def update_formation(app_id_or_name : String, formation_batch_update_request : FormationBatchUpdateRequest? = nil)
      data, _status_code, _headers = update_formation_with_http_info(app_id_or_name, formation_batch_update_request)
      data
    end

    # batch update formation
    # Batch update process formation (Heroku-compatible)
    # @param app_id_or_name [String] App ID or name
    # @return [Array<(Hash(String, Object), Integer, Hash)>] Hash(String, Object) data, response status code and response headers
    def update_formation_with_http_info(app_id_or_name : String, formation_batch_update_request : FormationBatchUpdateRequest? = nil)
      if @api_client.config.debugging
        Log.debug {"Calling API: FormationApi.update_formation ..."}
      end
      # verify the required parameter "app_id_or_name" is set
      if @api_client.config.client_side_validation && app_id_or_name.nil?
        raise ArgumentError.new("Missing the required parameter 'app_id_or_name' when calling FormationApi.update_formation")
      end
      # resource path
      local_var_path = "/api/v1/apps/{app_id_or_name}/formation".sub("{" + "app_id_or_name" + "}", URI.encode_path(app_id_or_name.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = formation_batch_update_request.to_json

      # return_type
      return_type = "Hash(String, Object)"

      # auth_names
      auth_names = ["bearer", "oauth2"]

      data, status_code, headers = @api_client.call_api(:PATCH,
                                                        local_var_path,
                                                        :"FormationApi.update_formation",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: FormationApi#update_formation\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Hash(String, Object).from_json(data), status_code, headers
    end
  end
end
