# #Build.io API V1
#
##No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

require "uri"

module Build
  class PipelinePromotionsApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # create a pipeline promotion
    # Creates a promotion from a source app to one or more target apps. Returns immediately with pending status — clients poll GET .../promotions/:id for completion.
    # @param pipeline_id [String] Pipeline ID
    # @return [PipelinePromotion]
    def create_pipeline_promotion(pipeline_id : String, create_pipeline_promotion_request : CreatePipelinePromotionRequest? = nil)
      data, _status_code, _headers = create_pipeline_promotion_with_http_info(pipeline_id, create_pipeline_promotion_request)
      data
    end

    # create a pipeline promotion
    # Creates a promotion from a source app to one or more target apps. Returns immediately with pending status — clients poll GET .../promotions/:id for completion.
    # @param pipeline_id [String] Pipeline ID
    # @return [Array<(PipelinePromotion, Integer, Hash)>] PipelinePromotion data, response status code and response headers
    def create_pipeline_promotion_with_http_info(pipeline_id : String, create_pipeline_promotion_request : CreatePipelinePromotionRequest? = nil)
      if @api_client.config.debugging
        Log.debug {"Calling API: PipelinePromotionsApi.create_pipeline_promotion ..."}
      end
      # verify the required parameter "pipeline_id" is set
      if @api_client.config.client_side_validation && pipeline_id.nil?
        raise ArgumentError.new("Missing the required parameter 'pipeline_id' when calling PipelinePromotionsApi.create_pipeline_promotion")
      end
      # resource path
      local_var_path = "/api/v1/pipelines/{pipeline_id}/promotions".sub("{" + "pipeline_id" + "}", URI.encode_path(pipeline_id.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = create_pipeline_promotion_request.to_json

      # return_type
      return_type = "PipelinePromotion"

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:POST,
                                                        local_var_path,
                                                        :"PipelinePromotionsApi.create_pipeline_promotion",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: PipelinePromotionsApi#create_pipeline_promotion\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return PipelinePromotion.from_json(data), status_code, headers
    end

    # get promotion status
    # Returns aggregate promotion status. Clients poll this until status is no longer pending.
    # @param pipeline_id [String] Pipeline ID
    # @param id [String] Promotion group ID
    # @return [PipelinePromotion]
    def get_pipeline_promotion(pipeline_id : String, id : String)
      data, _status_code, _headers = get_pipeline_promotion_with_http_info(pipeline_id, id)
      data
    end

    # get promotion status
    # Returns aggregate promotion status. Clients poll this until status is no longer pending.
    # @param pipeline_id [String] Pipeline ID
    # @param id [String] Promotion group ID
    # @return [Array<(PipelinePromotion, Integer, Hash)>] PipelinePromotion data, response status code and response headers
    def get_pipeline_promotion_with_http_info(pipeline_id : String, id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: PipelinePromotionsApi.get_pipeline_promotion ..."}
      end
      # verify the required parameter "pipeline_id" is set
      if @api_client.config.client_side_validation && pipeline_id.nil?
        raise ArgumentError.new("Missing the required parameter 'pipeline_id' when calling PipelinePromotionsApi.get_pipeline_promotion")
      end
      # verify the required parameter "id" is set
      if @api_client.config.client_side_validation && id.nil?
        raise ArgumentError.new("Missing the required parameter 'id' when calling PipelinePromotionsApi.get_pipeline_promotion")
      end
      # resource path
      local_var_path = "/api/v1/pipelines/{pipeline_id}/promotions/{id}".sub("{" + "pipeline_id" + "}", URI.encode_path(pipeline_id.to_s)).sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "PipelinePromotion"

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"PipelinePromotionsApi.get_pipeline_promotion",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: PipelinePromotionsApi#get_pipeline_promotion\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return PipelinePromotion.from_json(data), status_code, headers
    end

    # list promotion targets
    # Returns per-target status with error_message on failure.
    # @param pipeline_id [String] Pipeline ID
    # @param id [String] Promotion group ID
    # @return [Array(PromotionTarget)]
    def get_pipeline_promotion_targets(pipeline_id : String, id : String)
      data, _status_code, _headers = get_pipeline_promotion_targets_with_http_info(pipeline_id, id)
      data
    end

    # list promotion targets
    # Returns per-target status with error_message on failure.
    # @param pipeline_id [String] Pipeline ID
    # @param id [String] Promotion group ID
    # @return [Array<(Array(PromotionTarget), Integer, Hash)>] Array(PromotionTarget) data, response status code and response headers
    def get_pipeline_promotion_targets_with_http_info(pipeline_id : String, id : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: PipelinePromotionsApi.get_pipeline_promotion_targets ..."}
      end
      # verify the required parameter "pipeline_id" is set
      if @api_client.config.client_side_validation && pipeline_id.nil?
        raise ArgumentError.new("Missing the required parameter 'pipeline_id' when calling PipelinePromotionsApi.get_pipeline_promotion_targets")
      end
      # verify the required parameter "id" is set
      if @api_client.config.client_side_validation && id.nil?
        raise ArgumentError.new("Missing the required parameter 'id' when calling PipelinePromotionsApi.get_pipeline_promotion_targets")
      end
      # resource path
      local_var_path = "/api/v1/pipelines/{pipeline_id}/promotions/{id}/promotion-targets".sub("{" + "pipeline_id" + "}", URI.encode_path(pipeline_id.to_s)).sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "Array(PromotionTarget)"

      # auth_names
      auth_names = ["bearer"]

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"PipelinePromotionsApi.get_pipeline_promotion_targets",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        cookie_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: PipelinePromotionsApi#get_pipeline_promotion_targets\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Array(PromotionTarget).from_json(data), status_code, headers
    end
  end
end
