# #Build.io API V1
#
#### Authentication  All endpoints accept an OAuth Bearer token in the `Authorization` header.  Tokens come in three kinds, distinguished by their resource owner:  - **User tokens** (default) — full access to the user's apps, teams, pipelines, and namespaces. - **App-scoped tokens** (prefix `bldp_`) — bound to a single app. Can only access endpoints   that operate on that one app (e.g. `GET /api/v1/apps/:id`, builds, dynos, config vars).   Endpoints that operate on user-level collections (`/api/v1/apps`, `/api/v1/teams`,   `/api/v1/pipelines`, `/api/v1/namespaces`, `/api/v1/addon-attachments`, `/api/v1/addons`)   return **403 Forbidden** for these tokens. - **Addon partner tokens** (`addon:config` scope) — issued to addon vendors for partner   endpoints only.  The `/api/v1/me` response shape varies by token kind: user tokens return `{ email }`; app-scoped tokens return `{ app, email }` where `email` belongs to the user that minted the token.
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

# Dependencies
require "crest"
require "log"

module Build
  Log = ::Log.for("Build") # => Log for Build source

  VERSION = {{ `shards version #{__DIR__}`.chomp.stringify }}

  # Return the default `Configuration` object.
  def self.configure
    Configuration.default
  end

  # Customize default settings for the SDK using block.
  #
  # ```
  # Build.configure do |config|
  #   config.username = "xxx"
  #   config.password = "xxx"
  # end
  # ```
  def self.configure
    yield Configuration.default
  end
end

require "./build-client/**"
